//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEFEnt : DbContext
    {
        public projectEFEnt()
            : base("name=projectEFEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<outResiet> outResiets { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<suplyReset> suplyResets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<out_product> out_product { get; set; }
        public virtual DbSet<store_product> store_product { get; set; }
        public virtual DbSet<supply> supplies { get; set; }
        public virtual DbSet<custom> customs { get; set; }
        public virtual DbSet<in_product> in_product { get; set; }
    }
}
