//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplyReset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suplyReset()
        {
            this.in_product = new HashSet<in_product>();
        }
    
        public int num { get; set; }
        public string date { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> store_id { get; set; }
    
        public virtual store store { get; set; }
        public virtual supply supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<in_product> in_product { get; set; }
    }
}
