//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supply()
        {
            this.suplyResets = new HashSet<suplyReset>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<int> fax { get; set; }
        public Nullable<int> mobile { get; set; }
        public string email { get; set; }
        public string web { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suplyReset> suplyResets { get; set; }
    }
}
